[package]
name = "zenroom"
version = "0.3.0"
license = "AGPLv3"
description = "Zenroom bindings to execute Zencode inside Rust"
authors = ["Denis Roio <J@dyne.org>"]
edition = "2018"

[build-dependencies]
bindgen = "0.59.2"

[dev-dependencies]
serde_json = "1.0.74"
