[package]
name = "zenroom"
version = "0.3.0"
license = "AGPL-3.0-only"
description = "Zenroom bindings to execute Zencode inside Rust"
homepage = "https://zenroom.org"
repository = "https://github.com/dyne/zenroom"
documentation = "https://dev.zenroom.org"
authors = ["Denis Roio <J@dyne.org>"]
edition = "2018"

[build-dependencies]
bindgen = "0.59.2"

[dev-dependencies]
serde_json = "1.0.74"
