name: Build cortex-arm target

on: [push, pull_request]

jobs:
  coverity-scan:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: install dependencies
        run: |
          sudo apt install gcc-arm-none-eabi zsh qemu-system-arm 
      - name: Checkout submodules
        uses: textbook/git-checkout-submodule-action@master
      - name: build cortex-arm target 
        run: |
          make cortex-arm
      - name: Run cortex-m check
        run: |
          make check-cortex-m
