name: Test
on: [push]
env:
  EM_VERSION: 1.39.15
  EM_CACHE_FOLDER: 'emsdk-cache'
  EMSCRIPTEN: 'emsdk-cache'

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: bindings/javascript
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - uses: mymindstorm/setup-emsdk@v6
        with:
          version: ${{env.EM_VERSION}}
          actions-cache-folder: ${{env.EM_CACHE_FOLDER}}
      - run: emcc -v
      - run: yarn
      - run: yarn build
      - run: yarn test
