name: Lua linting
on:
  push:
    branches:
      - master 
    paths:
    - 'src/lua/**'
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: nebularg/actions-luacheck@v1
        with:
          path: 'src/lua'
          args: -std lua53 -config .luacheckrc
          annotate: 'warning'
