name: Build Zenroom using meson
on: [push, pull_request]

jobs:
  test:
    name: Build
    strategy:
      matrix:
        compiler: [clang-9, clang-10, clang-11, gcc-7, gcc-8, gcc-9, gcc-10]
        os: [ubuntu-latest, macos-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - uses: seanmiddleditch/gha-setup-ninja@master

      - name: Install compiler and dependencies on 🐧 Ubuntu
        if: matrix.os == "ubuntu-latest"
        run: |
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test
          sudo apt-get update
          # install compiler
          sudo apt-get install --force-yes ${{ matrix.compiler }}
          # install deps
          sudo apt-get install --force-yes cmake vim zsh luajit lua-cjson

      - name: Install compiler and dependencies on 🍏 macOS
        if: matrix.os == "macos-latest"
        run: |
          brew install cmake vim zsh luajit lua-cjson

      - name: Install meson
        run: pip3 install meson

      - name: Build using meson
        env:
          CC: ${{ matrix.compiler }}
        run: |
          meson build builddir && ninja -C builddir

      - name: Run tests
        run: |
          ninja -C builddir test
