name: Create and publish a Docker image

on:
  push:
    tags:
      - 'v*'

jobs:
  publish_docker_image:
    name: 🐳 Publish Docker image
    needs: semantic-release
    uses: ForkbombEu/workflows/.github/workflows/publish-ghcr.yml@main
    secrets: inherit
